### PR TITLE
Updated COPYING

### PR DESCRIPTION
**Pull request by mikaku**
Refreshed from https://www.gnu.org/licenses/old-licenses/lgpl-2.0.txt.
It had incorrect FSF address.

### CODE REVIEW

**Comment by mikaku** [comment]
This fix is necessary to continue with the acceptance of a new Fedora package for `smf-spf`.
You can track it [here](https://bugzilla.redhat.com/show_bug.cgi?id=1877006).

**Comment by mikaku** [comment]
Any idea why these checks are failing?

**Comment by jcbf** [comment]
I had some issues with some tests in Travis. Don't know why but timed out. 
That's why I moved to Github actions. I didn't port all the successful actions . Let me check!

**Comment by jcbf** [comment]
I can't understand why but I made a similar PR and worked fine. Maybe this PR caught me when I was tunning GitHub Actions.

**Comment by mikaku** [comment]
I can't close this PR, clone again your repository and create a new PR, if that helps.
Just let me know.

**Pull request merged**
